app/Http/routes.php
<?php

/*Route::group( [ 'prefix' => 'api/v1/', 'namespace' => 'Api' ], function () {
	Route::get( 'sliders', [ 'uses' => 'SliderController@getSliders' ] );
} );*/

Route::group(['prefix' => 'api/v1', 'namespace' => 'Api'], function () {
	Route::get('/sliders', array(
			'as' => 'sliders',
			'uses' => 'SliderController@getSliders')
	);
	Route::get('/slider/{id}', array(
			'as' => 'slider',
			'uses' => 'SliderController@getSlider')
	);
});


Route::group( [ 'middleware' => 'web' ], function () {
	Route::get( '/', function () {
		return 'Please redirect to auth/admin/login';
	} );

	/**
	 * Admin Auth
	 */
	Route::controller( 'auth/admin', 'Auth\AdminAuthController' );

	/**
	 * Admin
	 */
	Route::group( [ 'namespace' => 'Admin', 'middleware' => 'auth:admin', 'prefix' => 'admin' ], function () {
		Route::get( '/', [
			'as' => 'admin',
			function () {
				return redirect( action( 'Admin\DashboardController@getIndex' ) );
			}
		] );

		Route::controller( 'dashboard', 'DashboardController' );
		Route::controller( 'admin', 'AdminController' );
		Route::controller( 'festival', 'FestivalController' );
		Route::controller( 'slider', 'SliderController' );
	} );
} );

app/Models/Partner.php
<?php

namespace Sehramiz\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Sehramiz\Classes\EloquentPriceTrait;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class Partner extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable, CanResetPassword, EloquentPriceTrait;

    protected $table = 'partners';

    protected $primaryKey = 'partner_id';

    protected $hidden = ['password', 'remember_token', 'api_key'];

    public function getFullNameAttribute()
    {
        return "$this->name $this->last_name";
    }

    public function ipRestrict()
    {
        return $this->hasMany('Sehramiz\Models\PartnerIpRestrict', 'partner_id', 'partner_id');
    }
}

app/Models/PartnerCreditEvent.php
<?php

namespace Sehramiz\Models;

use Illuminate\Database\Eloquent\Model;
use Sehramiz\Classes\EloquentPriceTrait;
use Sehramiz\Classes\EloquentPaymentTrait;
use Sehramiz\Classes\EloquentTimestampJalaliTrait;

class PartnerCreditEvent extends Model
{
    use EloquentPriceTrait
    ,   EloquentPaymentTrait
    ,   EloquentTimestampJalaliTrait;

    protected $table = 'partners_credit_events';

    protected $primaryKey = 'partner_credit_event_id';

    public $timestamps = true;

    public function getCodeMessageAttribute()
    {
        return trans('general-words.partner_credit_event_'.$this->code);
    }
}

resources/views/admin/partner/create.blade.php
    @extends('admin.layout.main')

    @section('title', 'ایجاد همکار جدید')

    @section('content')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">همکار‌ها</h1>
            <div class="panel panel-default">
                <div class="panel-heading">ایجاد همکار جدید
                    <a class="btn btn-default btn-xs pull-left" href="{{action('Admin\PartnerController@getIndex')}}" title="برگشت"><i class="fa fa-reply"></i></a>
                </div>
                <div class="panel-body">
                    <form action="{{action('Admin\PartnerController@postCreate')}}" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <div class="col-md-12">
                                <label>نام @required</label>
                            </div>
                            <div class="col-md-4">
                                {!! Form::text('name', '', ['class' => 'form-control', 'required']) !!}
                                {!! $errors->first('name', "<p class='text text-danger'>:message</p>") !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <label>نام خانوادگی</label>
                            </div>
                            <div class="col-md-4">
                                {!! Form::text('last_name', '', ['class' => 'form-control']) !!}
                                {!! $errors->first('last_name', "<p class='text text-danger'>:message</p>") !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <label>ایمیل</label>
                            </div>
                            <div class="col-md-5">
                                {!! Form::text('email', '', ['class' => 'form-control en ltr']) !!}
                                {!! $errors->first('email', "<p class='text text-danger'>:message</p>") !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <label>موبایل</label>
                            </div>
                            <div class="col-md-3">
                                {!! Form::text('mobile', '', ['class' => 'form-control en ltr']) !!}
                                {!! $errors->first('mobile', "<p class='text text-danger'>:message</p>") !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <label>نام کاربری @required</label>
                            </div>
                            <div class="col-md-4">
                                {!! Form::text('username', '', ['class' => 'form-control en ltr', 'required']) !!}
                                {!! $errors->first('username', "<p class='text text-danger'>:message</p>") !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <label>رمز عبور @required</label>
                            </div>
                            <div class="col-md-4">
                                {!! Form::password('password', ['class' => 'form-control en ltr', 'required']) !!}
                                {!! $errors->first('password', "<p class='text text-danger'>:message</p>") !!}
                            </div>
                            <div class="col-md-12">
                                <p class="text-warning">حداقل طول رمز 8 کاراکتر</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <label>تایید رمز عبور @required</label>
                            </div>
                            <div class="col-md-4">
                                {!! Form::password('password_confirmation', ['class' => 'form-control en ltr', 'required']) !!}
                                {!! $errors->first('password_confirmation', "<p class='text text-danger'>:message</p>") !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <label>حداقل میزان اعتبار @required</label>
                            </div>
                            <div class="col-md-4">
                                <div class="input-group">
                                    {!! Form::text('minimum_credit', '0', ['class' => 'form-control en ltr p-sep-ltr', 'required']) !!}
                                    <div class="input-group-addon">ریال</div>
                                </div>
                                {!! $errors->first('minimum_credit', "<p class='text text-danger'>:message</p>") !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12">
                                <label>آواتار</label>
                            </div>
                            <div class="col-md-5">
                                <input name="avatar" type="file" class="form-control">
                                {!! $errors->first('avatar', "<p class='text text-danger'>:message</p>") !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12">
                                <label>آی‌پی‌ها</label>
                            </div>
                            <div class="col-md-5">
                                {!! Form::textarea('ip', '', ['class' => 'form-control en ltr']) !!}
                            </div>
                            <div class="col-md-12">
                                <p class="text-warning">هر IP در یک سطر</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <label>وضعیت</label>
                            </div>
                            <div class="col-md-2">
                                <label>غیر فعال</label>
                                {!! Form::radio('status', '0', true, ['class' => 'icheck-status disable']) !!}
                                <label>فعال</label>
                                {!! Form::radio('status', '1', false, ['class' => 'icheck-status enable']) !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="_token" value="{{csrf_token()}}">
                            <div class="col-md-6 text-right">
                                <a href="{{action('Admin\PartnerController@getIndex')}}" class="btn btn-default">برگشت</a>
                            </div>
                            <div class="col-md-6 text-left">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i> ایجاد کن</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @stop

resources/views/admin/partner/edit.blade.php
@extends('admin.layout.main')

@section('title', 'ویرایش همکار')

@section('content')
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">همکار‌ها
            @include('admin.partner.navigation')
        </h1>
        <div class="panel panel-default">
            <div class="panel-heading">ویرایش همکار
                <a class="btn btn-default btn-xs pull-left" href="{{action('Admin\PartnerController@getIndex')}}" title="برگشت"><i class="fa fa-reply"></i></a>
            </div>
            <div class="panel-body">
                <form action="{{action('Admin\PartnerController@postUpdate')}}" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>نام @required</label>
                        </div>
                        <div class="col-md-4">
                            {!! Form::text('name', $partner->name, ['class' => 'form-control', 'required']) !!}
                            {!! $errors->first('name', "<p class='text text-danger'>:message</p>") !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>نام خانوادگی</label>
                        </div>
                        <div class="col-md-4">
                            {!! Form::text('last_name', $partner->last_name, ['class' => 'form-control']) !!}
                            {!! $errors->first('last_name', "<p class='text text-danger'>:message</p>") !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>ایمیل</label>
                        </div>
                        <div class="col-md-5">
                            {!! Form::text('email', $partner->email, ['class' => 'form-control en ltr']) !!}
                            {!! $errors->first('email', "<p class='text text-danger'>:message</p>") !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>موبایل</label>
                        </div>
                        <div class="col-md-3">
                            {!! Form::text('mobile', $partner->mobile, ['class' => 'form-control en ltr']) !!}
                            {!! $errors->first('mobile', "<p class='text text-danger'>:message</p>") !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>نام کاربری @required</label>
                        </div>
                        <div class="col-md-4">
                            {!! Form::text('username', $partner->username, ['class' => 'form-control en ltr', 'required']) !!}
                            {!! $errors->first('username', "<p class='text text-danger'>:message</p>") !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>رمز عبور</label>
                        </div>
                        <div class="col-md-4">
                            {!! Form::password('password', ['class' => 'form-control en ltr']) !!}
                            {!! $errors->first('password', "<p class='text text-danger'>:message</p>") !!}
                        </div>
                        <div class="col-md-12">
                            <p class="text-warning">اگر مایل به تغییر رمز نیستید، این فیلد را خالی رها کنید.</p>
                            <p class="text-warning">حداقل طول رمز 8 کاراکتر</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>تایید رمز عبور</label>
                        </div>
                        <div class="col-md-4">
                            {!! Form::password('password_confirmation', ['class' => 'form-control en ltr']) !!}
                            {!! $errors->first('password_confirmation', "<p class='text text-danger'>:message</p>") !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>حداقل میزان اعتبار @required</label>
                        </div>
                        <div class="col-md-4">
                            <div class="input-group">
                                {!! Form::text('minimum_credit', $partner->minimum_credit, ['class' => 'form-control en ltr p-sep-ltr', 'required']) !!}
                                <div class="input-group-addon">ریال</div>
                            </div>
                            {!! $errors->first('minimum_credit', "<p class='text text-danger'>:message</p>") !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <label>آواتار</label>
                        </div>
                        <div class="col-md-5">
                            <input name="avatar" type="file" class="form-control">
                            @if ($partner->avatar)
                            <br>
                            <div class="row">
                                <div class="col-md-6">
                                    <ul class="none-begard-remove-selected" data-name="avatar_removed" data-value="1">
                                        <li>
                                            <span class="remove"><a class="btn btn-xs btn-warning" href="javascript:void(0)"><i class="fa fa-times"></i></a></span>
                                            <span class="image"><img class="img-thumbnail" src="{{URL::asset(Manage::uploadDir('partners').$partner->partner_id.'.'.$partner->avatar)}}"></span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            @endif
                            {!! $errors->first('avatar', "<p class='text text-danger'>:message</p>") !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <label>آی‌پی‌ها</label>
                        </div>
                        <div class="col-md-5">
                            {!! Form::textarea('ip', $ip, ['class' => 'form-control en ltr']) !!}
                        </div>
                        <div class="col-md-12">
                            <p class="text-warning">هر IP در یک سطر</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>وضعیت</label>
                        </div>
                        <div class="col-md-2">
                            <label>غیر فعال</label>
                            {!! Form::radio('status', '0', $partner->status == 0 ? true : false, ['class' => 'icheck-status disable']) !!}
                            <label>فعال</label>
                            {!! Form::radio('status', '1', $partner->status == 1 ? true : false, ['class' => 'icheck-status enable']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                        <input type="hidden" name="partner_id" value="{{$partner->partner_id}}">
                        <div class="col-md-6 text-right">
                            <a href="{{action('Admin\PartnerController@getIndex')}}" class="btn btn-default">برگشت</a>
                        </div>
                        <div class="col-md-6 text-left">
                            <button type="submit" class="btn btn-info"><i class="fa fa-pencil"></i> ذخیره</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/partner/index.blade.php
@extends('admin.layout.main')

@section('title', 'لیست همکاران')

@section('content')
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">همکاران</h1>
        <div class="panel panel-default">
            <div class="panel-heading">لیست همکاران</div>
            <div class="panel-body">
                <p class="text-left"><a class="btn btn-success" href="{{action('Admin\PartnerController@getCreate')}}"><i class="fa fa-plus"></i> همکار جدید</a></p>
                @if (Session::has('f-message'))
                    <div class="alert alert-{{Session::get('f-message')['t']}}">
                        {!! Session::get('f-message')['m'] !!}
                    </div>
                @endif

                <table class="table table-bordered table-hover custom-datatable">
                    <thead>
                        <tr>
                            <th class="en">#</th>
                            <th>نام</th>
                            <th>وضعیت</th>
                            <th>عملیات</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($partners as $partner)
                        <tr>
                            <td class="en">{{$partner->partner_id}}</td>
                            <td>{{"$partner->name $partner->last_name"}}</td>
                            <td><span class="label label-{{checkStatus($partner->status, 'success', 'danger')}}">{{checkStatus($partner->status, 'فعال', 'غیر فعال')}}</span></td>
                            <td>
                                <a href="{{action('Admin\PartnerController@getView', $partner->partner_id)}}" class="btn btn-primary btn-xs" title="مشاهده"><i class="fa fa-eye"></i></a>
                                <a href="{{action('Admin\PartnerController@getUpdate', $partner->partner_id)}}" class="btn btn-info btn-xs" title="ویرایش"><i class="fa fa-pencil"></i></a>
                                <a href="{{action('Admin\PartnerController@getDestroy', $partner->partner_id)}}" class="btn btn-danger btn-xs confirm" title="حذف"><i class="fa fa-times"></i></a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@stop

@section('footer')
<script>
    $('.custom-datatable').DataTable( {
        responsive: true,
        language: window.datatableLanguage,
        order: [[ 0, "desc" ]],
    });
</script>
@stop

resources/views/admin/partner/navigation.blade.php
<div class="pool-helper">
    <div class="input-group">
        <div class="input-group-btn">
            <a href="{{action('Admin\PartnerController@getView', $partner->partner_id)}}" class="btn btn-sm btn-default"><i class="fa fa-user"></i> {{$partner->name}}</a>
            <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                <li><a href="{{action('Admin\PartnerCreditController@getIndex')}}?partner_id={{$partner->partner_id}}" class="text-right"><i class="fa fa-credit-card"></i> اعتبارات</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{{action('Admin\PartnerController@getUpdate', $partner->partner_id)}}" class="text-right"><i class="fa fa-pencil"></i> ویرایش همکار</a></li>
            </ul>
        </div>
    </div>
</div>

resources/views/admin/partner/view.blade.php
@extends('admin.layout.main')

@section('title', 'مشاهده اطلاعات همکار')

@section('content')
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">مشاهده اطلاعات همکار
            @include('admin.partner.navigation')
        </h1>
        <div class="panel panel-default">
            <div class="panel-heading">مشاهده اطلاعات همکار
                <a class="btn btn-default btn-xs pull-left" href="{{action('Admin\PartnerController@getIndex')}}" title="برگشت"><i class="fa fa-reply"></i></a>
            </div>
            <div class="panel-body">
                @if (Session::has('f-message'))
                    <div class="alert alert-{{Session::get('f-message')['t']}}">
                        {!! Session::get('f-message')['m'] !!}
                    </div>
                @endif
                <div class="text-left">
                    <div class="dropdown">
                        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">عملیات‌ها <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="{{action('Admin\PartnerCreditController@getIncrease', $partner->partner_id)}}" class="text-right"><i class="fa fa-plus-square"></i> افزایش اعتبار</a></li>
                            <li><a href="{{action('Admin\PartnerCreditController@getDecrease', $partner->partner_id)}}" class="text-right"><i class="fa fa-minus-square"></i> عودت اعتبار</a></li>
                        </ul>
                    </div>
                </div>
                @if (!is_null($partner->avatar))
                <img src="{{URL::to(Manage::uploadDir('partners').$partner->partner_id.'.'.$partner->avatar)}}" class="img-thumbnail pull-left" style="margin: 10px 0;">
                @endif
                <h1>{{$partner->name}}</h1>
                <h3>اطلاعات کلی</h3>
                <table class="table table-bordered table-hover datatable">
                    <tr>
                        <th class="active">آی‌دی:</th>
                        <td class="en">{{$partner->partner_id}}</td>

                        <th class="active">نام:</th>
                        <td>{{"$partner->name $partner->last_name"}}</td>
                    </tr>
                    <tr>
                        <th class="active">نام کاربری</th>
                        <td>{{$partner->username}}</td>

                        <th class="active">وضعیت</th>
                        <td><span class="label label-{{checkStatus($partner->status, 'success', 'danger')}}">{{checkStatus($partner->status, 'فعال', 'غیر فعال')}}</span></td>
                    </tr>
                    <tr>
                        <th class="active">ایمیل:</th>
                        <td class="ltr">
                            <span class="en">{{$partner->email}}</span>
                        </td>

                        <th class="active">موبایل:</th>
                        <td class="ltr">
                            <span class="en">{{$partner->mobile}}</span>
                        </td>
                    </tr>
                    <tr>
                        <th class="active">اعتبار:</th>
                        <td class="success">
                            {{$partner->credit_admin}} ریال
                        </td>

                        <th class="active">کد API</th>
                        <td class="en">{{$partner->api_key}}</td>
                    </tr>
                </table>
                @if ($ips->count() > 0)
                <h3>آی‌پی‌ها</h3>
                <table class="table table-bordered table-hover">
                @foreach ($ips->chunk(4) as $ip)
                    <tr>
                    @foreach ($ip as $i)
                        <td>{{$i}}</td>
                    @endforeach
                    </tr>
                @endforeach
                </table>
                @endif
                @if ($creditEvents->count() > 0)
                <h3>
                    5 تغییرات آخر در اعتبار
                    <small><a href="{{action('Admin\PartnerCreditController@getIndex')}}?partner_id={{$partner->partner_id}}">مشاهده همه</a></small>
                </h3>
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>تاریخ</th>
                            <th>نوع عملیات</th>
                            <th>مبلغ</th>
                            <th>وضعیت</th>
                            <th>عملیات</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($creditEvents as $event)
                        <tr>
                            <td class="ltr text-right">{{$event->created_at_jalali}}</td>
                            <td>{{$event->code_message}}</td>
                            <td>{{$event->price_admin}} ریال</td>
                            <td><span class="label label-{{$event->payment_status_code}}">{{$event->payment_status_message}}</span></td>
                            <td>
                                <a href="{{action('Admin\PartnerCreditController@getView', $event->partner_credit_event_id)}}" class="btn btn-primary btn-xs" title="مشاهده"><i class="fa fa-eye"></i></a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                @endif
            </div>
        </div>
    </div>
</div>
@stop